on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      # Do a full checkout (all branches)
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: dealmore/gh-action-terraform-module-release@main
        with:
          upstream-branch: main
          release-branch: release
          release-tag: ${{ github.event.inputs.tag }}
          exclude: '["src/*"]'
